// src/angular/projects/sol/src/lib/sol.component.ts
import { Component, EventEmitter, Inject, OnInit, Output, ViewEncapsulation, OnDestroy, Input, AfterViewInit } from '@angular/core'
import { Terminal } from 'xterm'
import { AmtTerminal, AMTRedirector, TerminalDataProcessor, ConsoleLogger, Protocol, LogLevel } from '@open-amt-cloud-toolkit/ui-toolkit/core'
import { ActivatedRoute } from '@angular/router'
import { C, V, SPACE } from '@angular/cdk/keycodes'

@Component({
  selector: 'amt-sol',
  templateUrl: './sol.component.html',
  styleUrls: ['./sol.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class SolComponent implements OnInit, OnDestroy, AfterViewInit {
  uuid: string = ''
  terminal: any
  container!: any
  term: any
  redirector: any
  dataProcessor: any
  token: any
  server: string = ''
  mpsServer: boolean
  logger: ConsoleLogger = new ConsoleLogger(LogLevel.ERROR)
  @Output() deviceStatus: EventEmitter<number> = new EventEmitter<number>()
  @Input() deviceConnection: EventEmitter<boolean> = new EventEmitter<boolean>()

  constructor (@Inject('userInput') public params, private readonly activatedRoute: ActivatedRoute) {
    this.token = localStorage.getItem('loggedInUser')
    this.server = `${this.urlConstructor()}/relay`
    this.mpsServer = this.params.mpsServer.includes('/mps')
    if (this.mpsServer) {
      this.server = `${this.urlConstructor()}/ws/relay`
    }
  }

  urlConstructor (): string {
    return this.params.mpsServer.replace('http', 'ws')
  }

  ngOnInit (): void {
    this.activatedRoute.params.subscribe(params => {
      this.uuid = params.id
    })
    this.deviceConnection.subscribe((data: boolean) => {
      if (data) {
        this.init()
      } else {
        this.stopSol()
      }
    })
  }

  ngAfterViewInit (): void {
    this.init()
  }

  init (): void {
    this.instantiate()
    setTimeout(() => {
      this.startSol()
    }, 4000)
  }

  instantiate (): void {
    this.terminal = new AmtTerminal()
    this.dataProcessor = new TerminalDataProcessor(this.terminal)
    this.redirector = new AMTRedirector(this.logger, Protocol.SOL, new FileReader(), this.uuid, 16994, '', '', 0, 0, JSON.parse(this.token).token, this.server)
    this.terminal.onSend = this.redirector.send.bind(this.redirector)
    this.redirector.onNewState = this.terminal.StateChange.bind(this.terminal)
    this.redirector.onStateChanged = this.onTerminalStateChange.bind(this)
    this.redirector.onProcessData = this.dataProcessor.processData.bind(this)
    this.dataProcessor.processDataToXterm = this.handleWriteToXterm.bind(this)
    this.dataProcessor.clearTerminal = this.handleClearTerminal.bind(this)
    this.container = document.getElementById('terminal')
    this.term = new Terminal({
      rows: 30,
      cols: 100,
      cursorStyle: 'block',
      fontWeight: 'bold'
    })
    this.term.open(this.container)
    this.term.onData((data: any) => {
      this.handleKeyPress(data)
    })
    this.term.attachCustomKeyEventHandler((e: any) => {
      e.stopPropagation()
      e.preventDefault()
      if (e.ctrlKey === true && e.shiftKey === true && e.keyCode === C) {
        return navigator.clipboard.writeText(this.term.getSelection())
      } else if (e.ctrlKey === true && e.shiftKey === true && e.keyCode === V) {
        return navigator.clipboard.readText().then(text => {
          this.handleKeyPress(text)
        })
      } else if (e.code === SPACE) {
        return this.handleKeyPress(e.key)
      }
    })
  }

  handleKeyPress (domEvent: any): void {
    this.terminal.TermSendKeys(domEvent)
  }

  handleClearTerminal (): void {
    this.term.reset()
  }

  handleWriteToXterm (str: string): void {
    this.term.write(str)
  }

  onTerminalStateChange (redirector: AMTRedirector, state: number): void {
    this.deviceStatus.emit(state)
  }

  startSol (): void {
    if (this.redirector !== null) {
      this.redirector.start(WebSocket)
    }
  }

  stopSol (): void {
    if (this.redirector !== null) {
      this.redirector.stop()
      this.handleClearTerminal()
      this.term.dispose()
      this.cleanup()
    }
  }

  cleanup (): void {
    this.terminal = null
    this.redirector = null
    this.dataProcessor = null
    this.term = null
  }

  ngOnDestroy (): void {
    this.stopSol()
  }
}

<div class="container">
    <div id="terminal" class="xtermDisplay" style="width: fit-content;"></div>
</div>

// src/reactjs/components/SerialOverLAN/Sol.tsx
/*********************************************************************
* Copyright (c) Intel Corporation 2019
* SPDX-License-Identifier: Apache-2.0
**********************************************************************/

import React from 'react'
import { AmtTerminal } from '../../../core/AMTTerminal'
import Style from 'styled-components'
import { AMTRedirector, Protocol } from '../../../core/AMTRedirector'
import { ConsoleLogger } from '../../../core/ConsoleLogger'
import { LogLevel } from '../../../core'
import { TerminalDataProcessor } from '../../../core/TerminalDataProcessor'
import { Terminal } from 'xterm'
import Term from './Terminal'
import 'xterm/css/xterm.css'
import './sol.scss'

const StyledDiv = Style.div`
display : inline-block;
padding : 0px 5px;
`

const HeaderStrip = Style.div`
background-color: darkgray;
padding: 5px;
font-size: 13px;
text-align: center;
`

export interface SOLProps {
  deviceId: string | null
  mpsServer: string | null
  autoConnect?: boolean
}

export interface SOLStates {
  isConnected: boolean
  SOLstate: number
  powerState: number
  showSuccess: boolean
  message: string
  isSelected: boolean
  type: string
  solNotEnabled: string
  deviceOnSleep: string
  isPowerStateLoaded: boolean
}

/** container class for SOL */
export class Sol extends React.Component<SOLProps, SOLStates> {
  redirector: any
  terminal: any
  logger: any
  dataProcessor: any
  callback: any
  term: any
  fr: FileReader
  constructor (props: SOLProps) {
    super(props)
    this.logger = new ConsoleLogger(LogLevel.ERROR)
    this.state = {
      isConnected: false,
      SOLstate: 0,
      powerState: 0,
      showSuccess: false,
      message: '',
      isSelected: true,
      type: '',
      solNotEnabled: '',
      deviceOnSleep: '',
      isPowerStateLoaded: false
    }
  }

  init = (): void => {
    const server: string = this.props.mpsServer != null ? this.props.mpsServer.replace('http', 'ws') : ''
    const deviceUuid: string = this.props.deviceId != null ? this.props.deviceId : ''
    this.terminal = new AmtTerminal()
    this.redirector = new AMTRedirector(
      this.logger,
      Protocol.SOL,
      new FileReader(),
      deviceUuid,
      16994,
      '',
      '',
      0,
      0,
      `${server}/relay`
    )
    this.dataProcessor = new TerminalDataProcessor(this.terminal)
    this.terminal.onSend = this.redirector.send.bind(this.redirector)
    this.redirector.onNewState = this.terminal.StateChange.bind(this.terminal)
    this.redirector.onStateChanged = this.onTerminalStateChange.bind(this)
    this.redirector.onProcessData = this.dataProcessor.processData.bind(this.dataProcessor)
    this.dataProcessor.processDataToXterm = this.handleWriteToXterm.bind(this)
    this.dataProcessor.clearTerminal = this.handleClearTerminal.bind(this)
    this.term = new Terminal({
      cursorStyle: 'block',
      fontWeight: 'bold',
      rows: 30,
      cols: 100
    })
  }

  cleanUp = (): void => {
    this.terminal = null
    this.redirector = null
    this.dataProcessor = null
    this.term = null
  }

  componentDidMount (): void {
    this.init()
  }

  /** write the processed data from webscoket in to xterm */

  handleWriteToXterm = (str): any => this.term.write(str)

  handleClearTerminal = (): any => this.term.reset()

  /** capture the data on xterm key press */
  handleKeyPress = (domEvent): any => this.terminal.TermSendKeys(domEvent)

  handleKeyDownPress = (domEvent): any => this.terminal.handleKeyDownEvents(domEvent)

  startSOL = (): void => {
    if (typeof this.redirector !== 'undefined') {
      this.redirector.start(WebSocket)
    }
  }

  stopSOL = (): void => {
    if (typeof this.redirector !== 'undefined') {
      this.redirector.stop()
    }
    this.handleClearTerminal()
    this.cleanUp()
    this.init()
  }

  handleSOLConnect = (e): void => {
    e.persist()
    if (this.state.SOLstate === 0) {
      this.startSOL()
    } else {
      this.stopSOL()
    }
  }

  onTerminalStateChange = (redirector, state: number): void => this.setState({ SOLstate: state })

  /** callback functions from child components to update the state values */
  handleFeatureStatus = (value): void => {
    this.setState({
      solNotEnabled: value
    })
  }

  getSOLState = (): any => this.state.SOLstate === 3 ? 2 : 0

  render (): React.ReactNode {
    const { SOLstate } = this.state
    return (
      <React.Fragment>
        <HeaderStrip>
          <StyledDiv>
            <button onClick={this.handleSOLConnect}>{SOLstate === 3 ? 'Disconnect' : 'Connect'}</button>
          </StyledDiv>
        </HeaderStrip>
        {SOLstate === 3 && this.term && <Term handleKeyPress={this.handleKeyPress} handleKeyDownPress={this.handleKeyDownPress} xterm={this.term} />}
      </React.Fragment>
    )
  }
}
